### ISSUE TITLE
enable docsearch

### ISSUE THREAD

**Issue by maxheld83** [subugoe/hoad#82]
needs to be published on master first

**Comment by maxheld83** [comment]
mmh, last current guess for what's going on here are the (actually excluded) articles now deleted in https://github.com/subugoe/hoad/commit/30aab2a70cb8907a24049a86056b931de0d67463.

It's a bit weird, because these *did* show up in the **rendered** `pkgdown.yml`, as here for a `vignettes/_foo.Rmd`:

```
pandoc: 2.9.2.1
pkgdown: 1.5.1
pkgdown_sha: ~
articles:
  _foo: _foo.html
  about: about.html
  interactive: interactive.html
last_built: 2020-06-02T16:00Z
urls:
  reference: http://subugoe.github.io/hoad/reference
  article: http://subugoe.github.io/hoad/articles
```

I don't know who/what is using `pkgdown.yml` or whether algolia/docsearch does, but this doesn't smell right.
There shouldn't be such an entry in here, and because the `_foo.html` *doesn't actually exist*, whatever parses / relies on this `pkgdown.yml` could trip.

I've asked algolia/docsearch to try indexing the site yet again, without this potential snafu.

Either way, I'm going to log this on pkgdown.
